# Generated by Django 5.1.5 on 2025-05-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoRLCP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ids_respuestas', models.TextField()),
                ('patron_promedio', models.TextField()),
                ('cantidad_miembros', models.IntegerField()),
            ],
            options={
                'db_table': 'grupos_rlcp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LimeSurvey583965',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=36, null=True)),
                ('submitdate', models.DateTimeField(blank=True, null=True)),
                ('lastpage', models.IntegerField(blank=True, null=True)),
                ('startlanguage', models.CharField(max_length=20)),
                ('seed', models.CharField(blank=True, max_length=31, null=True)),
                ('edad', models.TextField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('universidad', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_de_curso', models.CharField(blank=True, db_column='tipo de curso', max_length=20, null=True)),
                ('carrera', models.CharField(blank=True, max_length=50, null=True)),
                ('año_academicco', models.CharField(blank=True, db_column='año academicco', max_length=5, null=True)),
                ('becado', models.CharField(blank=True, max_length=5, null=True)),
                ('trabajas', models.CharField(blank=True, max_length=5, null=True)),
                ('relacion_de_trabajo', models.CharField(blank=True, db_column='relacion de trabajo', max_length=15, null=True)),
                ('number_583965x17x432', models.CharField(blank=True, db_column='583965X17X432', max_length=5, null=True)),
                ('number_583965x17x433sq001', models.TextField(blank=True, db_column='583965X17X433SQ001', null=True)),
                ('number_583965x17x433sq002', models.TextField(blank=True, db_column='583965X17X433SQ002', null=True)),
                ('number_583965x21x436sq001', models.CharField(blank=True, db_column='583965X21X436SQ001', max_length=5, null=True)),
                ('number_583965x21x436sq002', models.CharField(blank=True, db_column='583965X21X436SQ002', max_length=5, null=True)),
                ('number_583965x21x436sq003', models.CharField(blank=True, db_column='583965X21X436SQ003', max_length=5, null=True)),
                ('number_583965x21x436sq004', models.CharField(blank=True, db_column='583965X21X436SQ004', max_length=5, null=True)),
                ('number_583965x21x436sq005', models.CharField(blank=True, db_column='583965X21X436SQ005', max_length=5, null=True)),
                ('number_583965x21x436sq006', models.CharField(blank=True, db_column='583965X21X436SQ006', max_length=5, null=True)),
                ('number_583965x21x436sq007', models.CharField(blank=True, db_column='583965X21X436SQ007', max_length=5, null=True)),
                ('number_583965x21x436sq008', models.CharField(blank=True, db_column='583965X21X436SQ008', max_length=5, null=True)),
                ('number_583965x21x436sq009', models.CharField(blank=True, db_column='583965X21X436SQ009', max_length=5, null=True)),
                ('number_583965x21x436sq010', models.CharField(blank=True, db_column='583965X21X436SQ010', max_length=5, null=True)),
                ('number_583965x21x436sq011', models.CharField(blank=True, db_column='583965X21X436SQ011', max_length=5, null=True)),
                ('number_583965x21x436sq012', models.CharField(blank=True, db_column='583965X21X436SQ012', max_length=5, null=True)),
                ('number_583965x21x436sq013', models.CharField(blank=True, db_column='583965X21X436SQ013', max_length=5, null=True)),
                ('number_583965x21x436sq014', models.CharField(blank=True, db_column='583965X21X436SQ014', max_length=5, null=True)),
                ('number_583965x21x436sq015', models.CharField(blank=True, db_column='583965X21X436SQ015', max_length=5, null=True)),
                ('number_583965x21x436sq016', models.CharField(blank=True, db_column='583965X21X436SQ016', max_length=5, null=True)),
                ('number_583965x21x436sq017', models.CharField(blank=True, db_column='583965X21X436SQ017', max_length=5, null=True)),
                ('number_583965x21x436sq018', models.CharField(blank=True, db_column='583965X21X436SQ018', max_length=5, null=True)),
                ('number_583965x21x436sq019', models.CharField(blank=True, db_column='583965X21X436SQ019', max_length=5, null=True)),
                ('number_583965x21x436sq020', models.CharField(blank=True, db_column='583965X21X436SQ020', max_length=5, null=True)),
                ('number_583965x21x436sq021', models.CharField(blank=True, db_column='583965X21X436SQ021', max_length=5, null=True)),
                ('number_583965x21x436sq022', models.CharField(blank=True, db_column='583965X21X436SQ022', max_length=5, null=True)),
                ('number_583965x21x436sq023', models.CharField(blank=True, db_column='583965X21X436SQ023', max_length=5, null=True)),
                ('number_583965x21x436sq024', models.CharField(blank=True, db_column='583965X21X436SQ024', max_length=5, null=True)),
                ('number_583965x21x436sq025', models.CharField(blank=True, db_column='583965X21X436SQ025', max_length=5, null=True)),
                ('number_583965x21x436sq026', models.CharField(blank=True, db_column='583965X21X436SQ026', max_length=5, null=True)),
                ('number_583965x21x436sq027', models.CharField(blank=True, db_column='583965X21X436SQ027', max_length=5, null=True)),
                ('number_583965x21x436sq028', models.CharField(blank=True, db_column='583965X21X436SQ028', max_length=5, null=True)),
                ('number_583965x21x436sq029', models.CharField(blank=True, db_column='583965X21X436SQ029', max_length=5, null=True)),
                ('number_583965x21x436sq030', models.CharField(blank=True, db_column='583965X21X436SQ030', max_length=5, null=True)),
                ('number_583965x21x436sq031', models.CharField(blank=True, db_column='583965X21X436SQ031', max_length=5, null=True)),
                ('number_583965x21x436sq032', models.CharField(blank=True, db_column='583965X21X436SQ032', max_length=5, null=True)),
                ('number_583965x20x430', models.CharField(blank=True, db_column='583965X20X430', max_length=5, null=True)),
                ('number_583965x20x430comment', models.TextField(blank=True, db_column='583965X20X430comment', null=True)),
            ],
            options={
                'db_table': 'lime_survey_583965',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptosGruposRLCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testor', models.CharField(max_length=255)),
                ('concepto', models.TextField()),
                ('concepto_general', models.TextField()),
                ('recomendacion', models.TextField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.gruporlcp')),
            ],
        ),
    ]
